#!/bin/bash

# https://opensource.com/article/19/10/programming-bash-logical-operators-shell-expansions

RAM=`free | grep ^Mem | awk '{print $2}'`

Swap=`free | grep ^Swap | awk '{print $2}'`

echo "RAM = $RAM and Swap = $Swap"
echo "Total Virtual memory is $((RAM+Swap))"
